from __future__ import annotations

WEB_CONTROL_PLANE_VERSION = 2
WEB_REFACTOR_PHASE = 8
WEB_FRONTEND = "vue3-shadcn-vue"
WEB_FRONTEND_MIGRATION_PHASE = 3

__all__ = [
    "WEB_CONTROL_PLANE_VERSION",
    "WEB_REFACTOR_PHASE",
    "WEB_FRONTEND",
    "WEB_FRONTEND_MIGRATION_PHASE",
]
